
services:
  backend:
    build: 
      context: .
      dockerfile: ./apps/y-system-server/Dockerfile

    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production

  frontend:
    build: 
      context: .
      dockerfile: ./apps/y-system-client/Dockerfile
    volumes:
      - ./apps/y-system-client/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5173:5173"
    depends_on:
      - backend
